version: '3.9'
services:
  activemq:
    image: cloudunit/activemq-5.13:latest
    container_name: 'activemq'
    ports:
      - 8161:8161
      - 11099:11099
    volumes:
      - ./conf/activemq.xml:/opt/activemq/conf/activemq.xml
      - ./conf/jmx.password:/opt/activemq/conf/jmx.password      
      - ./bin/env:/opt/activemq/bin/env
